export const ORDER_DATA_LOADED = "ORDER_DATA_LOADED";
export const ORDER_STATUS_CHECKED = "ORDER_STATUS_CHECKED";
export const ORDER_STATUS_UPDATED = "ORDER_STATUS_UPDATED";
export const API_ERROR = "API_ERROR";